name = "espresso_pgo_wrapper"
version = "0.0.2"
description = "Simple wrapper around the espresso PGO tool"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
repository = { type = "github", user = "nathanjohnson320", repo = "espresso_pgo_wrapper" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_pgo = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.10"
